### PR TITLE
Adding the new flag to the G2P website

### PR DESCRIPTION
**Pull request by olaaustine**
Description: https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4265

### CODE REVIEW

**Review by at7 — COMMENTED** [review]
This is a very good start. I have a few suggestions:

-- the flag also needs to be seen by users that are not logged in
-- we can use the bootstrap library to format the flag: How about styling it as a label (label-info): https://getbootstrap.com/docs/3.3/components/#labels

**Comment by olaaustine** [comment]
> This is a very good start. I have a few suggestions:
> 
> -- the flag also needs to be seen by users that are not logged in
> -- we can use the bootstrap library to format the flag: How about styling it as a label (label-info): https://getbootstrap.com/docs/3.3/components/#labels

Okay noted, will get right to it and update. Thank you 😊

**Review by at7 — COMMENTED** [review]
That looks better! Thank you.
Before I merge could you please fix the indention. It will help with the readability if we are consistent.
the % should be aligned and then `<p>` should start after 2 spaces:
```
% if ($gfd->{restricted_mutation} == 1){
  <p><span class="label label-info">Restricted repertoire of mutations</span></p>
% }
```

**Review by at7 — APPROVED** [review]
Looks good now. Thank you

**Pull request merged**
